import {defineType, defineField} from 'sanity'

export default defineType({
  name: 'course',
  title: 'Course',
  type: 'document',
  fields: [
    defineField({
      name: 'code',
      title: 'Course Code',
      type: 'string',
      description: 'e.g., ASA 101 or Bundle',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      description: 'e.g., Basic Keelboat Sailing',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {source: 'code', maxLength: 96},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'tagline',
      title: 'Tagline',
      type: 'string',
      description: 'Short marketing line',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'summary',
      title: 'Summary',
      type: 'text',
      rows: 2,
      description: '1-2 sentence blurb for listings',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'array',
      of: [{type: 'block'}],
      description: 'Full course description',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'learningOutcomes',
      title: 'What You\'ll Learn',
      type: 'array',
      of: [{type: 'string'}],
      description: 'Bulleted list of learning outcomes',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'duration',
      title: 'Duration',
      type: 'string',
      description: 'e.g., 3 days or 3 days (2 nights aboard)',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'schedule',
      title: 'Schedule',
      type: 'string',
      description: 'e.g., 9am - 5pm',
    }),
    defineField({
      name: 'boat',
      title: 'Boat',
      type: 'reference',
      to: [{type: 'boat'}],
      description: 'Training vessel for this course',
    }),
    defineField({
      name: 'maxStudents',
      title: 'Max Students',
      type: 'number',
      validation: (rule) => rule.required().min(1).max(10),
    }),
    defineField({
      name: 'womenOnlyAvailable',
      title: 'Women-Only Sessions Available',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'priceFrom',
      title: 'Price From',
      type: 'number',
      description: 'Display price (actual price managed in FareHarbor)',
      validation: (rule) => rule.required().min(0),
    }),
    defineField({
      name: 'priceNote',
      title: 'Price Note',
      type: 'string',
      description: 'e.g., 15% discount included',
    }),
    defineField({
      name: 'bookingType',
      title: 'Booking Type',
      type: 'string',
      options: {
        list: [
          {title: 'Online Booking', value: 'online'},
          {title: 'Call to Book', value: 'call-to-book'},
        ],
        layout: 'radio',
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'bookingFlowId',
      title: 'Booking Flow ID',
      type: 'string',
      description: 'FareHarbor booking flow ID (leave empty for call-to-book)',
      hidden: ({document}) => document?.bookingType === 'call-to-book',
    }),
    defineField({
      name: 'prerequisites',
      title: 'Prerequisites',
      type: 'string',
      description: 'e.g., ASA 101 + 103',
    }),
    defineField({
      name: 'certification',
      title: 'Certification',
      type: 'string',
      description: 'e.g., ASA 101 Basic Keelboat Sailing',
    }),
    defineField({
      name: 'isBundle',
      title: 'Is Bundle',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'bundleIncludes',
      title: 'Bundle Includes',
      type: 'string',
      description: 'e.g., ASA 101 + 103 + 104',
      hidden: ({document}) => !document?.isBundle,
    }),
    defineField({
      name: 'image',
      title: 'Course Image',
      type: 'image',
      options: {hotspot: true},
    }),
    defineField({
      name: 'sortOrder',
      title: 'Sort Order',
      type: 'number',
      description: 'Lower numbers appear first',
      validation: (rule) => rule.required(),
    }),
  ],
  orderings: [
    {
      title: 'Sort Order',
      name: 'sortOrderAsc',
      by: [{field: 'sortOrder', direction: 'asc'}],
    },
  ],
  preview: {
    select: {
      title: 'code',
      subtitle: 'title',
      media: 'image',
    },
  },
})
